version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:860061945305:task-definition/process-pension-microservice:6"
        LoadBalancerInfo:
          ContainerName: "process-pension-microservice"
          ContainerPort: "80"

        PlatformVersion: "LATEST"